config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # get "home/index"
  resources :resenas
  resources :prestamos
  resources :usuarios
  resources :libros
  resources :categoria
  resources :autors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/autor.rb
class Autor < ApplicationRecord
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: %i[ show edit update destroy ]

  # GET /autors or /autors.json
  def index
    @autors = Autor.all
  end

  # GET /autors/1 or /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors or /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to @autor, notice: "Autor was successfully created." }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1 or /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to @autor, notice: "Autor was successfully updated." }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1 or /autors/1.json
  def destroy
    @autor.destroy!

    respond_to do |format|
      format.html { redirect_to autors_path, status: :see_other, notice: "Autor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def autor_params
      params.require(:autor).permit(:nombre, :pais, :biografia, :fecha_nacimiento, :fecha_fallecimiento)
    end
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/views/autors/_autor.html.erb
<div id="<%= dom_id autor %>" class="usuario-info-container">
  <table class="usuario-info-table">
    <tr>
      <th>Nombre</th>
      <td><%= autor.nombre %></td>
    </tr>
    <tr>
      <th>Pais</th>
      <td><%= autor.pais %></td>
    </tr>
    <tr>
      <th>Biografia</th>
      <td><%= autor.biografia %></td>
    </tr>
    <tr>
      <th>Fecha nacimiento</th>
      <td><%= autor.fecha_nacimiento %></td>
    </tr>
    <tr>
      <th>Fecha fallecimiento</th>
      <td><%= autor.fecha_fallecimiento %></td>
    </tr>
  </table>
</div>

app/views/autors/_form.html.erb
<%= form_with(model: autor, class: "form-container") do |form| %>
  <% if autor.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(autor.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
        <% autor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre, class: "form-label" %>
    <%= form.text_field :nombre, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :pais, class: "form-label" %>
    <%= form.text_field :pais, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :biografia, class: "form-label" %>
    <%= form.text_area :biografia, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :fecha_nacimiento, class: "form-label" %>
    <%= form.date_field :fecha_nacimiento, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :fecha_fallecimiento, class: "form-label" %>
    <%= form.date_field :fecha_fallecimiento, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.submit "Guardar", class: "btn-primary" %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<% content_for :title, "Editing autor" %>

<h1>Editing autor</h1>

<%= render "form", autor: @autor %>

<br>

<div>
  <%= link_to "Ver autor", @autor, class: "btn" %> |
  <%= link_to "Ver lista", autors_path, class: "btn" %>
</div>

app/views/autors/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Autors" %>
<!-- Botón para volver a la página principal -->
<div class="back-button-container">
  <%= link_to "Volver a Inicio", root_path, class: "boton" %>
</div>

<h1>Autores</h1>

<div id="autors">
  <% @autors.each do |autor| %>
    <%= render autor %>
    <p>
      <%= link_to "Ver autor", autor, class: "btn" %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo autor", new_autor_path, class: "boton" %>

app/views/autors/new.html.erb
<% content_for :title, "Nuevo autor" %>

<h1>Nuevo autor</h1>

<%= render "form", autor: @autor %>

<br>

<div>
  <%= link_to "Ver lista", autors_path, class: "boton-inicio" %>
</div>

app/views/autors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @autor %>

<div>
  <%= link_to "Editar autor", edit_autor_path(@autor), class: "btn" %> |
  <%= link_to "Ver lista", autors_path, class: "btn" %>
  </br></br>
  <%= button_to "Eliminar autor", @autor, method: :delete, class: "boton" %>
</div>