config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # get "home/index"
  resources :resenas
  resources :prestamos
  resources :usuarios
  resources :libros
  resources :categoria
  resources :autors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/resena.rb
class Resena < ApplicationRecord
  belongs_to :libro
  belongs_to :usuario
end

app/controllers/resenas_controller.rb
class ResenasController < ApplicationController
  before_action :set_resena, only: %i[ show edit update destroy ]

  # GET /resenas or /resenas.json
  def index
    @resenas = Resena.all
  end

  # GET /resenas/1 or /resenas/1.json
  def show
  end

  # GET /resenas/new
  def new
    @resena = Resena.new
  end

  # GET /resenas/1/edit
  def edit
  end

  # POST /resenas or /resenas.json
  def create
    @resena = Resena.new(resena_params)

    respond_to do |format|
      if @resena.save
        format.html { redirect_to @resena, notice: "Resena was successfully created." }
        format.json { render :show, status: :created, location: @resena }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resena.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resenas/1 or /resenas/1.json
  def update
    respond_to do |format|
      if @resena.update(resena_params)
        format.html { redirect_to @resena, notice: "Resena was successfully updated." }
        format.json { render :show, status: :ok, location: @resena }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resena.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resenas/1 or /resenas/1.json
  def destroy
    @resena.destroy!

    respond_to do |format|
      format.html { redirect_to resenas_path, status: :see_other, notice: "Resena was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resena
      @resena = Resena.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resena_params
      params.require(:resena).permit(:libro_id, :usuario_id, :calificacion, :comentario, :fecha)
    end
end

app/helpers/resenas_helper.rb
module ResenasHelper
end

app/views/resenas/_form.html.erb
<%= form_with(model: resena, html: { class: "form-container" }) do |form| %>
  <% if resena.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(resena.errors.count, "error") %> impidieron guardar esta reseña:</h2>
      <ul>
        <% resena.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :libro_id, "ID del Libro:", class: "form-label" %>
    <%= form.text_field :libro_id, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :usuario_id, "ID del Usuario:", class: "form-label" %>
    <%= form.text_field :usuario_id, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :calificacion, "Calificación:", class: "form-label" %>
    <%= form.number_field :calificacion, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :comentario, "Comentario:", class: "form-label" %>
    <%= form.text_area :comentario, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :fecha, "Fecha:", class: "form-label" %>
    <%= form.date_field :fecha, class: "form-input" %>
  </div>

  <div class="form-actions">
    <%= form.submit "Guardar Reseña", class: "btn-primary" %>
  </div>
<% end %>

app/views/resenas/_resena.html.erb
<div id="<%= dom_id resena %>" class="usuario-info-container">
  <table class="usuario-info-table">
    <tr>
      <th>Libro</th>
      <td><%= resena.libro.titulo %></td>
    </tr>
    <tr>
      <th>Usuario</th>
      <td><%= resena.usuario.nombre %></td>
    </tr>
    <tr>
      <th>Calificación</th>
      <td><%= resena.calificacion %></td>
    </tr>
    <tr>
      <th>Comentario</th>
      <td><%= resena.comentario %></td>
    </tr>
    <tr>
      <th>Fecha</th>
      <td><%= resena.fecha %></td>
    </tr>
  </table>
</div>

app/views/resenas/edit.html.erb
<% content_for :title, "Editing resena" %>

<h1>Editar reseña</h1>

<%= render "form", resena: @resena %>

<br>

<div>
  <%= link_to "Ver reseña", @resena, class: "btn" %> |
  <%= link_to "Ver reseñas", resenas_path, class: "btn" %>
</div>

app/views/resenas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Resenas" %>
<!-- Botón para volver a la página principal -->
<div class="back-button-container">
  <%= link_to "Volver a Inicio", root_path, class: "boton" %>
</div>

<h1>Reseñas</h1>

<div id="resenas">
  <% @resenas.each do |resena| %>
    <%= render resena %>
    <p>
      <%= link_to "Ver reseña", resena, class: "btn" %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva reseña", new_resena_path, class: "boton" %>

app/views/resenas/new.html.erb
<% content_for :title, "New resena" %>

<h1>Nueva reseña</h1>

<%= render "form", resena: @resena %>

<br>

<div>
  <%= link_to "Ver reseñas", resenas_path, class: "boton" %>
</div>

app/views/resenas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @resena %>

<div>
  <%= link_to "Editar reseña", edit_resena_path(@resena), class: "btn" %> |
  <%= link_to "Ver reseñas", resenas_path, class: "btn" %>
  </br></br>
  <%= button_to "Eliminar reseña", @resena, method: :delete, class: "boton" %>
</div>