config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # get "home/index"
  resources :resenas
  resources :prestamos
  resources :usuarios
  resources :libros
  resources :categoria
  resources :autors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/prestamo.rb
class Prestamo < ApplicationRecord
  belongs_to :usuario
  belongs_to :libro
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController
  before_action :set_prestamo, only: %i[ show edit update destroy ]

  # GET /prestamos or /prestamos.json
  def index
    @prestamos = Prestamo.all
  end

  # GET /prestamos/1 or /prestamos/1.json
  def show
  end

  # GET /prestamos/new
  def new
    @prestamo = Prestamo.new
  end

  # GET /prestamos/1/edit
  def edit
  end

  # POST /prestamos or /prestamos.json
  def create
    @prestamo = Prestamo.new(prestamo_params)

    respond_to do |format|
      if @prestamo.save
        format.html { redirect_to @prestamo, notice: "Prestamo was successfully created." }
        format.json { render :show, status: :created, location: @prestamo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prestamos/1 or /prestamos/1.json
  def update
    respond_to do |format|
      if @prestamo.update(prestamo_params)
        format.html { redirect_to @prestamo, notice: "Prestamo was successfully updated." }
        format.json { render :show, status: :ok, location: @prestamo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamos/1 or /prestamos/1.json
  def destroy
    @prestamo.destroy!

    respond_to do |format|
      format.html { redirect_to prestamos_path, status: :see_other, notice: "Prestamo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prestamo
      @prestamo = Prestamo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prestamo_params
      params.require(:prestamo).permit(:usuario_id, :libro_id, :fecha_prestamo, :fecha_devolucion, :estado)
    end
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/views/prestamos/_form.html.erb
<%= form_with(model: prestamo, html: { class: "form-container" }) do |form| %>
  <% if prestamo.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(prestamo.errors.count, "error") %> impidieron guardar este préstamo:</h2>
      <ul>
        <% prestamo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :usuario_id, "ID del Usuario:", class: "form-label" %>
    <%= form.text_field :usuario_id, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :libro_id, "ID del Libro:", class: "form-label" %>
    <%= form.text_field :libro_id, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :fecha_prestamo, "Fecha de Préstamo:", class: "form-label" %>
    <%= form.date_field :fecha_prestamo, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :fecha_devolucion, "Fecha de Devolución:", class: "form-label" %>
    <%= form.date_field :fecha_devolucion, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :estado, "Estado:", class: "form-label" %>
    <%= form.text_field :estado, class: "form-input" %>
  </div>

  <div class="form-actions">
    <%= form.submit "Guardar Préstamo", class: " btn-primary" %>
  </div>
<% end %>

app/views/prestamos/_prestamo.html.erb
<div id="<%= dom_id prestamo %>" class="usuario-info-container">
  <table class="usuario-info-table">
    <tr>
      <th>Usuario</th>
      <td><%= prestamo.usuario.nombre %></td>
    </tr>
    <tr>
      <th>Libro</th>
      <td><%= prestamo.libro.titulo %></td>
    </tr>
    <tr>
      <th>Fecha préstamo</th>
      <td><%= prestamo.fecha_prestamo %></td>
    </tr>
    <tr>
      <th>Fecha devolución</th>
      <td><%= prestamo.fecha_devolucion %></td>
    </tr>
    <tr>
      <th>Estado</th>
      <td><%= prestamo.estado %></td>
    </tr>
  </table>
</div>

app/views/prestamos/edit.html.erb
<% content_for :title, "Editing prestamo" %>

<h1>Editar préstamo</h1>

<%= render "form", prestamo: @prestamo %>

<br>

<div>
  <%= link_to "Ver prestamo", @prestamo, class: "btn" %> |
  <%= link_to "Ver lista", prestamos_path, class: "btn" %>
</div>

app/views/prestamos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Prestamos" %>
<!-- Botón para volver a la página principal -->
<div class="back-button-container">
  <%= link_to "Volver a Inicio", root_path, class: "boton" %>
</div>
<h1>Préstamos</h1>

<div id="prestamos">
  <% @prestamos.each do |prestamo| %>
    <%= render prestamo %>
    <p>
      <%= link_to "Ver prestamo", prestamo, class: "btn" %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo prestamo", new_prestamo_path, class: "boton" %>

app/views/prestamos/new.html.erb
<% content_for :title, "New prestamo" %>

<h1>Nuevo prestamo</h1>

<%= render "form", prestamo: @prestamo %>

<br>

<div>
  <%= link_to "Ver lista", prestamos_path, class: "boton" %>
</div>

app/views/prestamos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @prestamo %>

<div>
  <%= link_to "Editar préstamo", edit_prestamo_path(@prestamo), class: "btn" %> |
  <%= link_to "Ver lista", prestamos_path, class: "btn" %>
  </br></br>
  <%= button_to "Eliminar préstamo", @prestamo, method: :delete, class: "boton" %>
</div>