config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # get "home/index"
  resources :resenas
  resources :prestamos
  resources :usuarios
  resources :libros
  resources :categoria
  resources :autors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/libro.rb
class Libro < ApplicationRecord
  belongs_to :autor
  belongs_to :categoria
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: %i[ show edit update destroy ]

  # GET /libros or /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1 or /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros or /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: "Libro was successfully created." }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1 or /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: "Libro was successfully updated." }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1 or /libros/1.json
  def destroy
    @libro.destroy!

    respond_to do |format|
      format.html { redirect_to libros_path, status: :see_other, notice: "Libro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def libro_params
      params.require(:libro).permit(:titulo, :isbn, :anio_publicacion, :autor_id, :categoria_id)
    end
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_with(model: libro, html: { class: "form-container" }) do |form| %>
  <% if libro.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(libro.errors.count, "error") %> impidieron guardar este libro:</h2>
      <ul>
        <% libro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :titulo, "Título:", class: "form-label" %>
    <%= form.text_field :titulo, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :isbn, "ISBN:", class: "form-label" %>
    <%= form.text_field :isbn, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :anio_publicacion, "Año de Publicación:", class: "form-label" %>
    <%= form.number_field :anio_publicacion, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :autor_id, "ID del Autor:", class: "form-label" %>
    <%= form.text_field :autor_id, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :categoria_id, "ID de la Categoría:", class: "form-label" %>
    <%= form.text_field :categoria_id, class: "form-input" %>
  </div>

  <div class="form-actions">
    <%= form.submit "Guardar Libro", class: "btn-primary" %>
  </div>
<% end %>

app/views/libros/_libro.html.erb
<div id="<%= dom_id libro %>" class="usuario-info-container">
  <table class="usuario-info-table">
    <tr>
      <th>Título</th>
      <td><%= libro.titulo %></td>
    </tr>
    <tr>
      <th>ISBN</th>
      <td><%= libro.isbn %></td>
    </tr>
    <tr>
      <th>Año publicación</th>
      <td><%= libro.anio_publicacion %></td>
    </tr>
    <tr>
      <th>Autor</th>
      <td><%= libro.autor.nombre %></td>
    </tr>
    <tr>
      <th>Categoría</th>
      <td><%= libro.categoria.nombre %></td>
    </tr>
  </table>
</div>

app/views/libros/edit.html.erb
<% content_for :title, "Editing libro" %>

<h1>Editing libro</h1>

<%= render "form", libro: @libro %>

<br>

<div>
  <%= link_to "Ver libro", @libro, class: "btn" %> |
  <%= link_to "Ver lista", libros_path, class: "btn" %>
</div>

app/views/libros/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Libros" %>
<!-- Botón para volver a la página principal -->
<div class="back-button-container">
  <%= link_to "Volver a Inicio", root_path, class: "boton" %>
</div>

<h1>Libros</h1>

<div id="libros">
  <% @libros.each do |libro| %>
    <%= render libro %>
    <p>
      <%= link_to "Ver libro", libro, class: "btn" %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo libro", new_libro_path, class: "boton" %>

app/views/libros/new.html.erb
<% content_for :title, "New libro" %>

<h1>Nuevo libro</h1>

<%= render "form", libro: @libro %>

<br>

<div>
  <%= link_to "Ver lista", libros_path, class: "boton" %>
</div>

app/views/libros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @libro %>

<div>
  <%= link_to "Editar libro", edit_libro_path(@libro), class: "btn" %> |
  <%= link_to "Ver lista", libros_path, class: "btn" %>
  </br></br>
  <%= button_to "Eliminar libro", @libro, method: :delete, class: "boton" %>
</div>